### ISSUE TITLE
Website Roadmap

### ISSUE THREAD

**Issue by igorlukanin** [vostok-project/website#1]
### Infrastructure

- [x] Register a domain name
- [x] Host and put online

### Content

Structure:
* Title, value, demo
* Features
* Fight insecurity & fear
* Call to action

#### Description

- [ ] Problem description
- [x] Name and generic word
- [x] One-line description
- [x] One-paragraph description
- [ ] Target audience
- [ ] Demo (?)
- [x] How it works
- [x] Features
- [ ] Same-platform competitors
- [ ] Similar solution on other platforms

#### Proofs

- [ ] Well-known users
- [ ] Testimonials
- [ ] Pros and cons
- [ ] Benchmarks
- [ ] Team
- [ ] Sponsors

#### Docs

- [x] Blueprint
- [x] Architecture overview
- [x] Getting started
- [ ] Installation tutorial
- [ ] Migration tutorial
- [ ] Sample project

#### Future

- [ ] Release history
- [ ] Roadmap

#### Misc

- [ ] Call to action

### Accessibility

- [ ] Favicon
- [ ] Open Graph previews
